# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gfunc_cpp <- function(ga) {
    .Call(`_bqrgal_gfunc_cpp`, ga)
}

dgal_cpp <- function(y, p0, mu, sigma, ga, logd = FALSE) {
    .Call(`_bqrgal_dgal_cpp`, y, p0, mu, sigma, ga, logd)
}

predBQRGAL_cpp <- function(mu, ga, sigma, ss, vv, AA, BB, CC, probs, err = FALSE, sam = FALSE) {
    .Call(`_bqrgal_predBQRGAL_cpp`, mu, ga, sigma, ss, vv, AA, BB, CC, probs, err, sam)
}

predBQRAL_cpp <- function(mu, sigma, vv, AA, BB, probs, err = FALSE, sam = FALSE) {
    .Call(`_bqrgal_predBQRAL_cpp`, mu, sigma, vv, AA, BB, probs, err, sam)
}

